default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>

development:
  <<: *default
  database: TFI-Ruby_development

test:
  <<: *default
  database: TFI-Ruby_test

production:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %> 

